//
// Created by eri on 8/28/21.
//

#ifndef GBA_GAMEDEV_ABSTRACT_REGISTER_ENUM_TEMPLATE_H
#define GBA_GAMEDEV_ABSTRACT_REGISTER_ENUM_TEMPLATE_H

#endif //GBA_GAMEDEV_ABSTRACT_REGISTER_ENUM_TEMPLATE_H
